DROP TABLE IF EXISTS profile CASCADE;

DROP TABLE IF EXISTS product CASCADE;

DROP TABLE IF EXISTS order_info CASCADE;

DROP TABLE IF EXISTS order_item;

DROP TABLE IF EXISTS category CASCADE;

DROP TABLE IF EXISTS shopping_cart_item;

DROP TABLE IF EXISTS cart;

DROP TABLE IF EXISTS promocode;

DROP TABLE IF EXISTS address;

DROP TABLE IF EXISTS favorite;

DROP TABLE IF EXISTS status;

DROP TABLE IF EXISTS comment;

DROP TABLE IF EXISTS survey CASCADE;

DROP TABLE IF EXISTS question_type CASCADE;

DROP TABLE IF EXISTS question CASCADE;

DROP TABLE IF EXISTS answer;

DROP TABLE IF EXISTS results;

DROP TABLE IF EXISTS messages;

DROP TABLE IF EXISTS activities;

